version: '3.4'

services:
  php:
   env_file:
     - .env
   build:
     context: .
     dockerfile: Dockerfile
   restart: always
   tty: true
   network_mode: 'bridge'
   volumes:
     - .:/var/www/html
   ports:
     - ${port}:80